### ISSUE TITLE
Responsive design issue

### ISSUE THREAD

**Issue by Atrix1987** [rakeshkatti/moengage#1]
The page has issues when opened on phone has headers overlapped with data

![screen shot 2015-03-30 at 10 30 30 am](https://cloud.githubusercontent.com/assets/2898596/6890405/25b3d6f2-d6c8-11e4-961d-0ea09ab9b14b.png)

**Comment by Atrix1987** [comment]
Responsive design issue with the add item template as well.

![device-2015-03-30-104302](https://cloud.githubusercontent.com/assets/2898596/6890474/a3e0d61e-d6c9-11e4-82a1-aa6d66c0ec46.png)

**Comment by rakeshkatti** [comment]
It was difficult to make material-ui framework responsive.
Will take care of this issue with flexbox grid or bootstrap.

**Comment by rakeshkatti** [comment]
I've taken care of this issue.
