### ISSUE TITLE
Empty template 

### ISSUE THREAD

**Issue by Atrix1987** [rakeshkatti/moengage#2]
When the page has loaded but react was not loaded , i.e. before the data was fetched it shows an empty template. It should rather show a load in progress view to provide proper UX
![screenshot_2015-03-30-10-33-58](https://cloud.githubusercontent.com/assets/2898596/6890440/e854863e-d6c8-11e4-8d34-c414a2715448.png)

**Comment by Atrix1987** [comment]
The same thing happens on a desktop with slow connection. Emulated on desktop with network set as 3G

**Comment by rakeshkatti** [comment]
I am trying find a way to understand how react and firebase interact. I'm not able find the point where the rendering is done. 

Firebase keeps updating the state. When I used componentDidUpdate method to get the point where rendering is done. Its landing up in a Maximum call stack error. 

Will try to understand this and update soon.

**Comment by Atrix1987** [comment]
https://www.firebase.com/docs/web/guide/retrieving-data.html

**Comment by rakeshkatti** [comment]
It was issue with my react code. I'm actually not allowed to set state on componentDidUpdate. 

I've fixed this. Also added a loading indicator which matches material-ui.
