### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by Atrix1987** [rakeshkatti/moengage#4]
The Validation is not restricted and the forms are allowed to be submitted even if the data is incorrect and form as error.
![screen shot 2015-03-30 at 10 56 04 am](https://cloud.githubusercontent.com/assets/2898596/6890571/845e3b9a-d6cb-11e4-8215-002d233d14c2.png)

**Comment by rakeshkatti** [comment]
Form will now not be submitted if the data is incorrect. And I've added other validations. First name cannot be more than 50 characters. Designation cannot be more than 100 characters.
