### ISSUE TITLE
Form input limits

### ISSUE THREAD

**Issue by Atrix1987** [rakeshkatti/moengage#5]
Inputs should have a limit in number of characters where ever it is applicable
![screen shot 2015-03-30 at 10 55 53 am](https://cloud.githubusercontent.com/assets/2898596/6890580/b8cb18ee-d6cb-11e4-9538-a1ad26bde184.png)

**Comment by rakeshkatti** [comment]
Limit has been fixed for name to 50 characters, Mobile to 10 and designation to 100 characters.
